image: gradle:8.3-jdk17-alpine

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

before_script:
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew clean assemble --no-build-cache
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .gradle
  artifacts:
    paths:
      - build/libs/
    expire_in: 1 week

test:
  stage: test
  script:
    - ./gradlew clean check
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .gradle
