INSERT INTO professions (id, name_)
VALUES
    (1, 'Maurer und Betonbauer'),
    (2, 'Ofen- und Luftheizungsbauer'),
    (3, 'Zimmerer'),
    (4, 'Dachdecker'),
    (5, 'Straßenbauer'),
    (6, 'Wärme-, Kälte- und Schallschutzisolierer'),
    (7, 'Brunnenbauer'),
    (8, 'Steinmetzen und Steinbildhauer'),
    (9, 'Stuckateure'),
    (10, 'Maler und Lackierer'),
    (11, 'Gerüstbauer'),
    (12, 'Schornsteinfeger'),
    (13, 'Metallbauer'),
    (14, 'Chirurgiemechaniker'),
    (15, 'Karosserie- und Fahrzeugbauer'),
    (16, 'Feinwerkmechaniker'),
    (17, 'Zweiradmechaniker'),
    (18, 'Kälteanlagenbauer'),
    (19, 'Informationstechniker'),
    (20, 'Kraftfahrzeugtechniker'),
    (21, 'Land- und Baumaschinenmechatroniker'),
    (22, 'Büchsenmacher'),
    (23, 'Klempner'),
    (24, 'Installateur und Heizungsbauer'),
    (25, 'Elektrotechniker'),
    (26, 'Elektromaschinenbauer'),
    (27, 'Tischler'),
    (28, 'Boots- und Schiffbauer'),
    (29, 'Seiler'),
    (30, 'Bäcker'),
    (31, 'Konditoren'),
    (32, 'Fleischer'),
    (33, 'Augenoptiker'),
    (34, 'Hörakustiker'),
    (35, 'Orthopädietechniker'),
    (36, 'Orthopädieschuhmacher'),
    (37, 'Zahntechniker'),
    (38, 'Friseure'),
    (39, 'Glaser'),
    (40, 'Glasbläser und Glasapparatebauer'),
    (41, 'Mechaniker für Reifen- und Vulkanisationstechnik'),
    (42, 'Fliesen-, Platten- und Mosaikleger'),
    (43, 'Werkstein- und Terrazzohersteller'),
    (44, 'Estrichleger'),
    (45, 'Behälter- und Apparatebauer'),
    (46, 'Parkettleger'),
    (47, 'Rollladen- und Sonnenschutztechniker'),
    (48, 'Drechsler (Elfenbeinschnitzer) und Holzspielzeugmacher'),
    (49, 'Böttcher'),
    (50, 'Glasveredler'),
    (51, 'Schilder- und Lichtreklamehersteller'),
    (52, 'Raumausstatter'),
    (53, 'Orgel- und Harmoniumbauer'),
    (54, 'Uhrmacher'),
    (55, 'Graveure'),
    (56, 'Metallbildner'),
    (57, 'Galvaniseure'),
    (58, 'Metall- und Glockengießer'),
    (59, 'Präzisionswerkzeugmechaniker'),
    (60, 'Gold- und Silberschmiede'),
    (61, 'Modellbauer'),
    (62, 'Holzbildhauer'),
    (63, 'Korb- und Flechtwerkgestalter'),
    (64, 'Maßschneider'),
    (65, 'Textilgestalter (Sticker, Weber, Klöppler, Posamentierer, Stricker)'),
    (66, 'Modisten'),
    (67, 'Segelmacher'),
    (68, 'Kürschner'),
    (69, 'Schuhmacher'),
    (70, 'Sattler und Feintäschner'),
    (71, 'Müller'),
    (72, 'Brauer und Mälzer'),
    (73, 'Weinküfer'),
    (74, 'Textilreiniger'),
    (75, 'Wachszieher'),
    (76, 'Gebäudereiniger'),
    (77, 'Feinoptiker'),
    (78, 'Glas- und Porzellanmaler'),
    (79, 'Edelsteinschleifer und -graveure'),
    (80, 'Fotografen'),
    (81, 'Buchbinder'),
    (82, 'Print- und Medientechnologen (Drucker, Siebdrucker, Flexografen)'),
    (83, 'Keramiker'),
    (84, 'Klavier- und Cembalobauer'),
    (85, 'Handzuginstrumentenmacher'),
    (86, 'Geigenbauer'),
    (87, 'Bogenmacher'),
    (88, 'Metallblasinstrumentenmacher'),
    (89, 'Holzblasinstrumentenmacher'),
    (90, 'Zupfinstrumentenmacher'),
    (91, 'Vergolder'),
    (92, 'Holz- und Bautenschützer (Mauerschutz und Holzimprägnierung in Gebäuden)'),
    (93, 'Bestatter'),
    (94, 'Kosmetiker'),
    (95, 'Eisenflechter'),
    (96, 'Bautentrocknungsgewerbe'),
    (97, 'Bodenleger'),
    (98, 'Asphaltierer (ohne Straßenbau)'),
    (99, 'Fuger (im Hochbau)'),
    (100, 'Rammgewerbe (Einrammen von Pfählen im Wasserbau)'),
    (101, 'Betonbohrer und -schneider'),
    (102, 'Theater- und Ausstattungsmaler'),
    (103, 'Herstellung von Drahtgestellen für Dekorationszwecke in Sonderanfertigung'),
    (104, 'Metallschleifer und Metallpolierer'),
    (105, 'Metallsägen-Schärfer'),
    (106, 'Tankschutzbetriebe (Korrosionsschutz von Öltanks für Feuerungsanlagen ohne chemische Verfahren)'),
    (107, 'Fahrzeugverwerter'),
    (108, 'Rohr- und Kanalreiniger'),
    (109, 'Kabelverleger im Hochbau (ohne Anschlussarbeiten)'),
    (110, 'Holzschuhmacher'),
    (111, 'Holzblockmacher'),
    (112, 'Daubenhauer'),
    (113, 'Holz-Leitermacher (Sonderanfertigung)'),
    (114, 'Muldenhauer'),
    (115, 'Holzreifenmacher'),
    (116, 'Holzschindelmacher'),
    (117, 'Einbau von genormten Baufertigteilen (zum Beispiel Fenster, Türen, Zargen, Regale)'),
    (118, 'Bürsten- und Pinselmacher'),
    (119, 'Bügelanstalten für Herren-Oberbekleidung'),
    (120, 'Dekorationsnäher (ohne Schaufensterdekoration)'),
    (121, 'Fleckteppichhersteller'),
    (122, 'Theaterkostümnäher'),
    (123, 'Plisseebrenner'),
    (124, 'Stoffmaler'),
    (125, 'Textil-Handdrucker'),
    (126, 'Kunststopfer'),
    (127, 'Änderungsschneider'),
    (128, 'Handschuhmacher'),
    (129, 'Ausführung einfacher Schuhreparaturen'),
    (130, 'Gerber'),
    (131, 'Innerei-Fleischer (Kuttler)'),
    (132, 'Speiseeishersteller (mit Vertrieb von Speiseeis mit üblichem Zubehör)'),
    (133, 'Fleischzerleger, Ausbeiner'),
    (134, 'Appreteure, Dekateure'),
    (135, 'Schnellreiniger'),
    (136, 'Teppichreiniger'),
    (137, 'Getränkeleitungsreiniger'),
    (138, 'Maskenbildner'),
    (139, 'Lampenschirmhersteller (Sonderanfertigung)'),
    (140, 'Klavierstimmer'),
    (141, 'Theaterplastiker'),
    (142, 'Requisiteure'),
    (143, 'Schirmmacher'),
    (144, 'Steindrucker'),
    (145, 'Schlagzeugmacher');