INSERT INTO it_component (id, name_, description, long_description, parent_id)
VALUES
    (200, 'IT-Komponenten', 'Alle technischen und digitalen Elemente im IT-Bereich.', 'IT-Komponenten umfasst alle technischen und digitalen Elemente im IT-Bereich.', NULL),
    (25, 'Hardware', 'Physische Computerkomponenten und -geräte.', 'Hardware bezieht sich auf physische Computerkomponenten und -geräte.', 200),
    (24, 'Netzwerkkomponenten', 'Geräte, die zur Verbindung und Kommunikation in Netzwerken verwendet werden.', 'Netzwerkkomponenten umfassen alle Geräte, die zur Verbindung und Kommunikation in Netzwerken verwendet werden.', 25),
    (15, 'Firewall', 'Schützt Netzwerke vor unerwünschtem Zugriff und Bedrohungen.', 'Eine Firewall schützt Netzwerke vor unerwünschtem Zugriff und Bedrohungen.', 24),
    (16, 'Internet Gateway', 'Ein Internet Gateway ermöglicht den Zugang zu und von externen Netzwerken.', '', 24),
    (17, 'Switch', 'Ein Switch verbindet verschiedene Geräte innerhalb eines lokalen Netzwerks.', '', 24),
    (18, 'Wireless Access Point', 'Ein Wireless Access Point ermöglicht kabellose Verbindungen zu einem Netzwerk.', '', 24),
    (19, 'Router', 'Ein Router leitet Datenpakete zwischen Netzwerken weiter.', '', 24),
    (20, 'Unterbrechungsfreie Stromversorgung', 'Eine USV bietet Notstromversorgung für elektronische Geräte.', '', 24),
    (21, 'Modem', 'Ein Modem modifiziert und demoduliert Signale für die Datenübertragung.', '', 24),
    (28, 'Computer & Mobile Geräte', 'Computer & Mobile Geräte umfassen alle Arten von Rechnern und tragbaren Geräten.', '', 25),
    (22, 'Computer', 'Computer sind elektronische Geräte zur Verarbeitung von Daten.', '', 28),
    (1, 'Desktop-Computer', 'Ein Desktop-Computer ist ein stationärer Personal Computer.', '', 22),
    (2, 'Laptop', 'Ein Laptop ist ein tragbarer Computer mit integriertem Bildschirm und Tastatur.', '', 22),
    (3, 'NAS', 'Ein NAS ist ein Netzwerkgerät zur Speicherung und Freigabe von Daten.', '', 22),
    (4, 'Datei-Server', 'Ein Datei-Server speichert und verwaltet Dateien für Netzwerkbenutzer.', '', 22),
    (5, 'Anwendungs-Server', 'Ein Anwendungs-Server stellt Anwendungen und Dienste für Nutzer bereit.', '', 22),
    (6, 'Netzwerkdrucker', 'Ein Netzwerkdrucker ermöglicht Druckaufträge über ein Netzwerk.', '', 22),
    (7, 'Teleworkstation', 'Eine Teleworkstation ermöglicht die Arbeit aus der Ferne mittels Telekommunikation.', '', 22),
    (8, 'Workstation', 'Eine Workstation ist ein leistungsstarker Computer für technische oder wissenschaftliche Anwendungen.', '', 22),
    (9, 'Cloud-hosted Virtual Machine', 'Eine Cloud-hosted Virtual Machine ist eine virtuelle Maschine, die in der Cloud betrieben wird.', '', 22),
    (10, 'Cloud-hosted Container Cluster', 'Ein Cloud-hosted Container Cluster verwaltet und orchestriert Container in der Cloud.', '', 22),
    (23, 'Mobile Geräte', 'Mobile Geräte sind tragbare elektronische Geräte wie Smartphones und Tablets.', '', 28),
    (11, 'Smartphone', 'Ein Smartphone ist ein multifunktionales Mobiltelefon mit Internetzugang.', '', 23),
    (12, 'Mobiltelefon', 'Mobile Telefone die keine Smartphones sind.', '', 23),
    (13, 'Tablet', 'Ein Tablet ist ein tragbarer Computer mit Touchscreen.', '', 23),
    (14, 'Smartwatch', 'Eine Smartwatch ist eine intelligente Uhr mit zusätzlichen Funktionen wie Benachrichtigungen.', '', 23),
    (29, 'Sicherheit und Monitoring', 'Sicherheit und Monitoring umfasst Systeme zur Überwachung und Sicherung von Ressourcen.', '', 25),
    (161, 'Intrusion Detection System (IDS)', 'Eine Sicherheitskomponente, die den Netzwerkverkehr überwacht und nach verdächtigen Aktivitäten oder Anomalien sucht, um auf potenzielle Eindringversuche oder Sicherheitsverletzungen hinzuweisen.', '', 29),
    (162, 'Intrusion Prevention System (IPS)', 'Eine Sicherheitskomponente, die den Netzwerkverkehr überwacht und aktiv eingreift, um potenzielle Eindringversuche oder Sicherheitsverletzungen zu blockieren oder zu verhindern.', '', 29),
    (163, 'Videoüberwachungssystem', 'Eine Hardwarekomponente, die zur visuellen Überwachung und Aufzeichnung von Aktivitäten in bestimmten Bereichen oder Gebäuden verwendet wird, um Sicherheitsvorfälle zu erkennen und zu dokumentieren.', '', 29),
    (164, 'Zutrittskontrollsystem', 'Ein System zur Sicherheitsüberwachung und -kontrolle, das den Zugang zu bestimmten Bereichen oder Ressourcen überprüft und steuert, um unbefugten Zugriff zu verhindern und die Sicherheit zu erhöhen.', '', 29),
    (165, 'Biometrisches Authentifizierungssystem', 'Ein Sicherheitssystem, das biometrische Merkmale wie Fingerabdrücke, Gesichtserkennung oder Iris-Scan verwendet, um die Identität von Personen zu überprüfen und den Zugang zu autorisierten Benutzern zu gewähren.', '', 29),
    (166, 'Sicherheitskameras', 'Hardwaregeräte, die zur visuellen Überwachung von Orten oder Umgebungen verwendet werden, um Sicherheitsvorfälle zu erkennen, aufzuzeichnen und zu überwachen.', '', 29),
    (167, 'Sicherheitsbeleuchtungssystem', 'Ein Beleuchtungssystem, das für die Sicherheit und Überwachung von Gebäuden oder Außenbereichen konzipiert ist und eine ausreichende Beleuchtung bietet, um potenzielle Sicherheitsrisiken zu reduzieren und die Sichtbarkeit zu verbessern.', '', 29),
    (33, 'Fertigungsmaschinen und Werkzeuge', 'Fertigungsmaschinen und Werkzeuge sind Geräte und Maschinen zur Produktion von Gütern.', '', 25),
    (168, 'CNC-Maschinen', 'Computerisierte Werkzeugmaschinen, die durch numerische Steuerung Befehle verarbeiten, um Materialien präzise zu bearbeiten und komplexe Teile herzustellen, insbesondere in der metallverarbeitenden Industrie.', '', 33),
    (169, '3D-Drucker', 'Eine additive Fertigungsmaschine, die digitale Modelle in physische Objekte umwandelt, indem sie Schichten von Materialien wie Kunststoff, Metall oder Keramik aufbaut, was eine flexible und schnelle Prototypenentwicklung ermöglicht.', '', 33),
    (170, 'CNC-Fräsmaschinen', 'Computerisierte Werkzeugmaschinen, die durch numerische Steuerung Befehle verarbeiten, um präzise Materialien zu schneiden, zu bohren oder zu fräsen, wodurch komplexe Formen und Teile hergestellt werden können.', '', 33),
    (171, 'Lasergravurmaschinen', 'Maschinen, die Laserstrahlen verwenden, um Materialien wie Holz, Kunststoff, Metall oder Glas zu markieren, schneiden oder gravieren, was in der Produktkennzeichnung, Personalisierung oder Prototypenherstellung eingesetzt wird.', '', 33),
    (172, 'Robotergesteuerte Fertigungssysteme', 'Automatisierte Fertigungssysteme, die industrielle Roboter einsetzen, um Materialien zu handhaben, zu bearbeiten oder zu montieren, wodurch die Produktivität gesteigert, Fehler reduziert und die Flexibilität in der Produktion erhöht werden.', '', 33),
    (173, 'CNC-Drehmaschinen', 'Computerisierte Werkzeugmaschinen, die durch numerische Steuerung Befehle verarbeiten, um präzise Rotationen von Materialien wie Metall oder Kunststoff durchzuführen, was zur Herstellung von zylindrischen Teilen oder Komponenten verwendet wird.', '', 33),
    (174, 'CNC-Schneidemaschinen', 'Computerisierte Werkzeugmaschinen, die durch numerische Steuerung Befehle verarbeiten, um präzise Schnitte in Materialien wie Metall, Kunststoff oder Holz durchzuführen, was in der Fertigung und Prototypenentwicklung eingesetzt wird.', '', 33),
    (175, 'Plasma-Schneidemaschinen', 'Maschinen, die Plasma verwenden, um Materialien wie Metall, Kunststoff oder Stein zu schneiden oder zu bearbeiten, was in der Metallverarbeitung, Automobilindustrie oder Bauwesen eingesetzt wird.', '', 33),
    (37, 'Steuerungsgeräte', 'Steuerungsgeräte sind Geräte zur Steuerung und Regelung von Maschinen und Prozessen.', '', 25),
    (176, 'Programmable Logic Controller (PLC)', 'Ein industrieller Steuerungscomputer, der zur Automatisierung von Maschinen und Prozessen eingesetzt wird, indem er digitale und analoge Signale verarbeitet und entsprechende Steuerbefehle ausführt.', '', 37),
    (177, 'Human-Machine Interface (HMI)', 'Ein Bedienfeld oder Touchscreen-Display, das eine grafische Benutzeroberfläche bietet, um die Interaktion zwischen Benutzern und Maschinen zu erleichtern, Steuerungsparameter einzustellen und Betriebsdaten anzuzeigen.', '', 37),
    (178, 'Distributed Control System (DCS)', 'Ein zentrales Steuerungssystem, das aus verteilten Steuereinheiten besteht, die miteinander verbunden sind, um Prozesse in verschiedenen Anlagenbereichen zu überwachen, zu steuern und zu optimieren, insbesondere in der Prozessindustrie.', '', 37),
    (179, 'Supervisory Control and Data Acquisition (SCADA)', 'Ein System zur Überwachung, Steuerung und Erfassung von Daten aus entfernten oder verteilten Anlagen oder Prozessen, das Echtzeitinformationen bereitstellt und die Automatisierung und Effizienz verbessert, insbesondere in der Industrie- und Energieerzeugung.', '', 37),
    (180, 'Industrial PC (IPC)', 'Ein robustes und zuverlässiges Computersystem, das speziell für den Einsatz in industriellen Umgebungen entwickelt wurde, um Steuerungs-, Überwachungs- und Automatisierungsaufgaben durchzuführen, wobei häufig Echtzeitverarbeitung erforderlich ist.', '', 37),
    (181, 'Motion Control System', 'Ein Steuersystem, das Bewegungen von Maschinen oder Anlagen präzise steuert und koordiniert, indem es Motoren, Antriebe und Sensoren verwendet, um Positionen, Geschwindigkeiten und Beschleunigungen zu regeln, insbesondere in automatisierten Produktionslinien oder Robotersystemen.', '', 37),
    (26, 'Software', 'Software umfasst alle Programme und Betriebssysteme, die auf Computern verwendet werden.', '', 200),
    (41, 'Betriebssysteme', 'Betriebssysteme verwalten die Hardware und Software eines Computers.', '', 26),
    (42, 'Windows', 'Windows ist ein Betriebssystem von Microsoft, das weit verbreitet in Personal Computern und Unternehmen verwendet wird und für seine Benutzerfreundlichkeit und breite Softwarekompatibilität bekannt ist.', '', 41),
    (43, 'Linux', 'Linux ist ein Open-Source-Betriebssystem, das für seine Stabilität, Sicherheit und Anpassungsfähigkeit geschätzt wird und häufig auf Servern, in der Softwareentwicklung und bei technikaffinen Nutzern eingesetzt wird.', '', 41),
    (44, 'MacOS', 'MacOS ist ein Betriebssystem von Apple, das exklusiv für Macintosh-Computer entwickelt wurde und für seine Benutzerfreundlichkeit, Integration mit anderen Apple-Geräten und kreativen Softwareanwendungen bekannt ist.', '', 41),
    (45, 'Standard Software', 'Standard Software sind weit verbreitete Programme für allgemeine Aufgaben.', '', 26),
    (101, 'Microsoft Office', 'Ein weit verbreitetes Softwarepaket für Desktop-Computer, das Anwendungen wie Word, Excel, PowerPoint und Outlook umfasst und für Textverarbeitung, Tabellenkalkulation, Präsentationen und E-Mail-Management genutzt wird.', '', 45),
    (102, 'Adobe Acrobat', 'Eine Desktop-Software zum Erstellen, Bearbeiten und Anzeigen von PDF-Dokumenten, die in vielen Büroumgebungen für die Dokumentenverwaltung und elektronische Signaturen verwendet wird.', '', 45),
    (103, 'QuickBooks Desktop', 'Eine Buchhaltungssoftware, die kleinen und mittelständischen Unternehmen bei der Verwaltung ihrer Finanzen, Rechnungsstellung, Gehaltsabrechnung und Steuerberichterstattung hilft.', '', 45),
    (104, 'LibreOffice', 'Ein Open-Source-Softwarepaket für Desktop-Computer, das Textverarbeitung, Tabellenkalkulation, Präsentationen, Zeichnungen und Datenbanken umfasst und als kostenlose Alternative zu Microsoft Office dient.', '', 45),
    (105, 'CorelDRAW', 'Eine Grafikdesign-Software, die für die Erstellung von Vektorgrafiken, Layouts, Bildbearbeitung und Webdesign genutzt wird und häufig in kreativen Büroumgebungen verwendet wird.', '', 45),
    (106, 'FileZilla', 'Ein FTP-Client, der auf Desktop-Computern verwendet wird, um Dateien zwischen einem lokalen Computer und einem Server zu übertragen und zu verwalten.', '', 45),
    (107, 'AutoCAD', 'Eine Software für computergestütztes Design (CAD), die in vielen Branchen für das Erstellen von präzisen 2D- und 3D-Zeichnungen und Entwürfen genutzt wird.', '', 45),
    (108, 'Mozilla Thunderbird', 'Ein Open-Source-E-Mail-Client für Desktop-Computer, der E-Mails, Newsfeeds, Newsgroups und Chats verwaltet und erweiterte Sicherheitsfunktionen bietet.', '', 45),
    (109, 'Microsoft Project', 'Eine Projektmanagement-Software für Desktop-Computer, die Tools zur Planung, Überwachung und Verwaltung von Projekten bietet und für die Ressourcenverwaltung und Terminplanung verwendet wird.', '', 45),
    (110, 'GIMP', 'Ein Open-Source-Bildbearbeitungsprogramm für Desktop-Computer, das für die Erstellung und Bearbeitung von Rastergrafiken und Fotos verwendet wird und eine kostengünstige Alternative zu Adobe Photoshop darstellt.', '', 45),
    (111, 'WinZip', 'Eine Dateikomprimierungs- und Archivierungssoftware für Desktop-Computer, die das Komprimieren, Entpacken und Verschlüsseln von Dateien und Ordnern ermöglicht.', '', 45),
    (112, 'Snagit', 'Eine Bildschirmaufnahme- und Bildbearbeitungssoftware für Desktop-Computer, die das Erfassen von Screenshots und die Aufnahme von Bildschirmvideos sowie die Bearbeitung und Kommentierung ermöglicht.', '', 45),
    (113, 'PaintShop Pro', 'Eine Bildbearbeitungssoftware für Desktop-Computer, die für die Fotobearbeitung, Grafikdesign und Bildoptimierung verwendet wird und erweiterte Tools zur Verbesserung und Anpassung von Bildern bietet.', '', 45),
    (114, 'ABBYY FineReader', 'Eine OCR-Software (Optical Character Recognition) für Desktop-Computer, die gedruckte Dokumente und PDFs in bearbeitbare und durchsuchbare digitale Dateien umwandelt.', '', 45),
    (49, 'Steuerungssoftware', 'Steuerungssoftware steuert und überwacht Maschinen und Prozesse.', '', 26),
    (115, 'Siemens SIMATIC STEP 7', 'Eine Engineering-Software für die Programmierung und Konfiguration von Siemens SIMATIC-Steuerungen, die in der Automatisierungstechnik verwendet wird.', '', 49),
    (116, 'Rockwell Automation Studio 5000', 'Eine Software-Suite für die Entwicklung und Verwaltung von Steuerungsprogrammen für Allen-Bradley-PLCs, die eine integrierte Entwicklungsumgebung bietet.', '', 49),
    (117, 'EcoStruxure Control Expert', 'Eine Programmiersoftware für Schneider Electric Modicon-PLCs, die Werkzeuge zur Entwicklung, Konfiguration und Wartung von Automatisierungssystemen bereitstellt.', '', 49),
    (118, 'Beckhoff TwinCAT', 'Eine Automatisierungssoftware für Beckhoff-Steuerungen, die sowohl eine Entwicklungsumgebung als auch ein Laufzeitsystem für Echtzeitanwendungen bietet.', '', 49),
    (119, 'B&R Automation Studio', 'Eine Entwicklungssoftware für die Programmierung und Konfiguration von B&R-Automatisierungssystemen, die integrierte Tools für die Projektentwicklung und Inbetriebnahme enthält.', '', 49),
    (53, 'IT-Sicherheitssoftware', 'IT-Sicherheitssoftware schützt Computer und Netzwerke vor Bedrohungen.', '', 26),
    (120, 'Symantec Endpoint Protection', 'Eine umfassende Endpoint-Sicherheitslösung, die Unternehmen vor Malware, Ransomware und anderen Bedrohungen schützt und eine zentrale Verwaltung bietet.', '', 53),
    (121, 'Cisco Firepower Threat Defense', 'Eine integrierte Sicherheitsplattform, die Netzwerke vor Bedrohungen schützt, fortschrittliche Bedrohungsabwehrfunktionen bietet und eine umfassende Transparenz und Kontrolle ermöglicht.', '', 53),
    (122, 'Palo Alto Networks Next-Generation Firewall', 'Eine Firewall-Lösung der nächsten Generation, die fortschrittliche Bedrohungserkennung, Inhaltsfilterung und VPN-Funktionen bietet, um Unternehmensnetzwerke zu schützen.', '', 53),
    (123, 'McAfee Total Protection', 'Eine umfassende Sicherheitslösung für Endgeräte, Netzwerke und die Cloud, die vor Viren, Malware, Phishing-Angriffen und Identitätsdiebstahl schützt.', '', 53),
    (124, 'Check Point SandBlast', 'Eine erweiterte Bedrohungserkennungs- und Sandboxing-Lösung, die Unternehmen vor bekannten und unbekannten Bedrohungen schützt und Angriffe auf Endpunkte, Netzwerke und Cloud-Ressourcen blockiert.', '', 53),
    (125, 'Fortinet FortiGate', 'Eine integrierte Sicherheitsplattform, die Netzwerke vor Bedrohungen schützt, Zugangskontrolle bietet und fortschrittliche Funktionen wie IPS, VPN und Webfilterung umfasst.', '', 53),
    (126, 'Trend Micro Deep Security', 'Eine Plattform für die Server- und Cloud-Sicherheit, die Schwachstellenmanagement, Intrusion Detection und Prevention, sowie Schutz vor Malware und Ransomware bietet.', '', 53),
    (127, 'Avast Antivirus', 'Eine Antivirensoftware für Desktop-Computer, die vor Viren, Malware, Spyware und anderen Bedrohungen schützt und regelmäßige Updates für die Erkennung neuer Bedrohungen bietet.', '', 53),
    (128, 'AVG Antivirus', 'Eine Antivirensoftware für Desktop-Computer, die eine Kombination aus Signatur- und Verhaltenserkennung verwendet, um vor Viren, Malware und anderen Bedrohungen zu schützen.', '', 53),
    (129, 'Norton Antivirus', 'Eine Antivirensoftware für Desktop-Computer, die fortschrittliche Bedrohungserkennung und Echtzeitschutz bietet und vor Viren, Malware, Ransomware und anderen Bedrohungen schützt.', '', 53),
    (130, 'Kaspersky Antivirus', 'Eine Antivirensoftware für Desktop-Computer, die vor Viren, Malware, Ransomware, Spyware und Phishing-Angriffen schützt und regelmäßige Updates für die Erkennung neuer Bedrohungen bereitstellt.', '', 53),
    (131, 'Bitdefender Antivirus', 'Eine Antivirensoftware für Desktop-Computer, die mehrschichtigen Schutz vor Viren, Malware, Ransomware und anderen Bedrohungen bietet und geringe Systemressourcen verbraucht.', '', 53),
    (57, 'Branchen-Software', 'Branchen-Software ist auf spezielle Bedürfnisse einer Branche zugeschnittene Software.', '', 26),
    (132, 'mfr', 'Ein Softwareprogramm für Handwerksbetriebe, das Funktionen wie Auftragsmanagement, Kundenverwaltung und Abrechnung bietet, um die Geschäftsabläufe zu optimieren.', '', 57),
    (133, 'dashandwerk.net', 'Eine cloudbasierte Handwerkersoftware, die Auftragsmanagement, Zeiterfassung und Dokumentation vereinfacht und die Kommunikation zwischen Handwerkern und Kunden verbessert.', '', 57),
    (134, 'das Programm', 'Eine All-in-One-Lösung für Handwerksbetriebe, die Angebots- und Rechnungserstellung, Auftragsabwicklung, Kundenverwaltung und Buchhaltung umfasst, um die Betriebsabläufe zu erleichtern.', '', 57),
    (135, 'craftboxx', 'Eine Handwerkersoftware mit Funktionen für Auftragsmanagement, Projektplanung, Ressourcenverwaltung und Rechnungsstellung, die die Produktivität steigert und die Verwaltungsaufgaben vereinfacht.', '', 57),
    (136, 'openhandwerk', 'Eine innovative Handwerkersoftware, die Auftragsabwicklung, Zeiterfassung, Materialverwaltung und Kommunikation mit Kunden vereinfacht und die Effizienz im Handwerksbetrieb verbessert.', '', 57),
    (137, 'blue:solution work ce', 'Eine Handwerkersoftware, die Auftragsmanagement, Kalkulation, Personalplanung und Dokumentation in einer benutzerfreundlichen Plattform vereint, um die Arbeitsabläufe zu optimieren.', '', 57),
    (138, 'tooltime', 'Eine Handwerkersoftware mit Funktionen für Auftragsverwaltung, Terminplanung, Materialbeschaffung und Rechnungserstellung, die die Effizienz im Handwerksbetrieb steigert und die Kundenkommunikation verbessert.', '', 57),
    (139, 'winworker', 'Eine umfassende Softwarelösung für Handwerksbetriebe, die Auftragsabwicklung, Personalmanagement, Materialbeschaffung und Buchhaltung vereinfacht, um die Geschäftsprozesse zu optimieren.', '', 57),
    (140, 'monteurplaner', 'Eine Handwerkersoftware für die effiziente Planung und Einsatzsteuerung von Montage- und Serviceteams, die Terminplanung, Routenoptimierung und Auftragsverwaltung bietet.', '', 57),
    (141, 'plancraft', 'Eine Softwarelösung für Handwerksbetriebe, die Projektmanagement, Ressourcenplanung, Kostenkalkulation und Dokumentation vereint, um die Projektabwicklung zu erleichtern und die Rentabilität zu steigern.', '', 57),
    (142, 'HERO - die Handwerkersoftware', 'Eine moderne Handwerkersoftware, die Auftragsmanagement, Personalplanung, Materialwirtschaft und Rechnungsstellung integriert und die Geschäftsabläufe effizienter gestaltet.', '', 57),
    (143, 'Lunds Büro', 'Eine Handwerkersoftware, die Angebots- und Rechnungserstellung, Auftragsverwaltung, Kundenkommunikation und Buchhaltung umfasst, um die Verwaltungsaufgaben zu vereinfachen und die Produktivität zu steigern.', '', 57),
    (144, 'JUPROWA Offa', 'Eine Softwarelösung für Handwerksbetriebe, die Auftragsmanagement, Projektplanung, Zeiterfassung und Buchhaltung in einem integrierten System vereint und die Geschäftsabläufe optimiert.', '', 57),
    (145, 'shm Handwerkersoftware', 'Eine umfassende Softwarelösung für Handwerksbetriebe, die Auftragsabwicklung, Materialwirtschaft, Personalmanagement und Buchhaltung vereint, um die Geschäftsprozesse zu optimieren.', '', 57),
    (146, 'Streit V.1', 'Eine Handwerkersoftware mit Funktionen für Auftragsmanagement, Kalkulation, Terminplanung und Dokumentation, die die Arbeitsabläufe im Handwerksbetrieb vereinfacht und die Rentabilität steigert.', '', 57),
    (61, 'Cloud-Services', 'Cloud-Services bieten Dienstleistungen und Ressourcen über das Internet an.', '', 26),
    (160, 'Google Workspace', 'Eine Suite von Cloud-basierten Produktivitäts-Tools, die E-Mail, Dokumentenbearbeitung, Kalender und Videokonferenzen umfasst und die Zusammenarbeit im Büro erleichtert.', '', 61),
    (147, 'Microsoft 365', 'Eine integrierte Suite von Cloud-Diensten, die E-Mail, Office-Anwendungen, Dateispeicherung und Zusammenarbeitstools bietet, um die Produktivität im Büro zu steigern.', '', 61),
    (148, 'Dropbox Business', 'Ein Cloud-Speicherdienst für Unternehmen, der Dateifreigabe, Kollaborationstools und sichere Datenverwaltung bietet, um die Effizienz im Büro zu verbessern.', '', 61),
    (149, 'Slack', 'Eine Plattform für Teamkommunikation, die Messaging, Dateifreigabe, Kanäle und Integrationen mit anderen Tools bietet, um die Zusammenarbeit im Büro zu fördern.', '', 61),
    (150, 'Zoom', 'Eine Cloud-basierte Videokonferenzplattform, die virtuelle Meetings, Webinare und Remote-Zusammenarbeit ermöglicht, um die Kommunikation im Büro zu erleichtern.', '', 61),
    (151, 'Trello', 'Eine Cloud-basierte Projektmanagement-Plattform, die visuelle Boards, Aufgabenlisten und Teamkollaboration bietet, um die Arbeitsabläufe im Büro zu organisieren und zu verfolgen.', '', 61),
    (152, 'Asana', 'Eine Cloud-basierte Projektmanagement-Software, die Aufgabenverfolgung, Teamkollaboration und Fortschrittsberichte bietet, um die Produktivität im Büro zu steigern.', '', 61),
    (153, 'Salesforce', 'Eine Cloud-basierte CRM-Plattform, die Vertriebsautomatisierung, Kundenservice und Marketingfunktionen bietet, um Kundenbeziehungen im Büro zu verwalten und zu verbessern.', '', 61),
    (154, 'Box', 'Ein Cloud-Speicherdienst für Unternehmen, der Dateifreigabe, Kollaboration und Content-Management bietet, um die Zusammenarbeit und Datensicherheit im Büro zu verbessern.', '', 61),
    (155, 'Adobe Creative Cloud', 'Eine Suite von Cloud-basierten Kreativtools, die Grafikdesign, Bildbearbeitung, Videobearbeitung und Webentwicklung umfasst, um kreative Projekte im Büro zu realisieren.', '', 61),
    (156, 'Evernote Business', 'Eine Cloud-basierte Notiz- und Organisationsplattform für Unternehmen, die Notizen, Aufgaben, Dokumente und Teamkollaboration bietet, um die Produktivität im Büro zu verbessern.', '', 61),
    (157, 'AWS', 'Amazon Web Services (AWS) ist eine Cloud-Computing-Plattform, die eine breite Palette von Diensten wie Computing, Datenbanken, Speicherung und künstliche Intelligenz bietet, um die IT-Infrastruktur im Büro zu unterstützen.', '', 61),
    (158, 'G Suite', 'Eine Suite von Cloud-basierten Produktivitäts-Tools, die E-Mail, Dokumentenbearbeitung, Kalender und Zusammenarbeitstools bietet, um die Arbeitsabläufe im Büro zu erleichtern und zu verbessern.', '', 61),
    (159, 'Zoho Office Suite', 'Eine Suite von Cloud-basierten Büroanwendungen, die E-Mail, Dokumentenbearbeitung, Tabellenkalkulation und Präsentationssoftware umfasst, um die Produktivität im Büro zu steigern.', '', 61),
    (27, 'Sonstiges', 'Sonstiges umfasst alle Komponenten, die in keine andere Kategorie passen.', '', 200),
    (50, 'Head-Mounted Display', 'Ein Head-Mounted Display ist ein tragbares Gerät für visuelle Ausgaben direkt vor den Augen.', '', 23),
    (182, 'Android Gerät', 'Smartphones und Tablets, die das Android-Betriebssystem nutzen.', '', 11),
    (183, 'iOS Gerät', 'Apple-Smartphones und -Tablets mit dem iOS-Betriebssystem', '', 11),
    (184, 'Web-Browser', 'Software zur Anzeige von Webseiten und Nutzung von Online-Diensten.', '', 26);

